import type { FontWeight, ITheme } from '@xterm/xterm';

export const terminalFontFamilyChoices: ReadonlyArray<{
  value: GuiSshAppSettings['terminalFontFamily'];
  label: string;
}> = [
  { value: 'Cascadia Mono', label: 'Cascadia Mono' },
  { value: 'JetBrains Mono', label: 'JetBrains Mono' },
  { value: 'Fira Code', label: 'Fira Code' },
  { value: 'Consolas', label: 'Consolas' },
  { value: 'LXGW WenKai Mono', label: 'LXGW WenKai Mono' },
  { value: 'Source Code Pro', label: 'Source Code Pro' },
  { value: 'Hack', label: 'Hack' },
  { value: 'Menlo', label: 'Menlo' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Courier New', label: 'Courier New' },
];

export const terminalThemeChoices: ReadonlyArray<{
  key: GuiSshAppSettings['terminalTheme'];
  label: string;
  summary: string;
  theme: ITheme;
}> = [
  {
    key: 'guissh-dark',
    label: 'GUI-SSH 暗色',
    summary: '高对比青绿，适合长时间 SSH 会话',
    theme: {
      background: '#181a24',
      foreground: '#d7fbe8',
      cursor: '#8cf7d5',
      cursorAccent: '#181a24',
      selectionBackground: '#29546f',
      selectionInactiveBackground: '#1f3c4f',
      scrollbarSliderBackground: '#d7fbe833',
      scrollbarSliderHoverBackground: '#d7fbe866',
      scrollbarSliderActiveBackground: '#d7fbe880',
      black: '#111827',
      red: '#ff6f8f',
      green: '#8cf7d5',
      yellow: '#ffe08a',
      blue: '#43c7ff',
      magenta: '#c084fc',
      cyan: '#67e8f9',
      white: '#edf4ff',
      brightBlack: '#4b5563',
      brightRed: '#ff8aa3',
      brightGreen: '#a7f3d0',
      brightYellow: '#fde68a',
      brightBlue: '#7dd3fc',
      brightMagenta: '#ddd6fe',
      brightCyan: '#a5f3fc',
      brightWhite: '#ffffff',
    },
  },
  {
    key: 'netcatty-dark',
    label: 'Netcatty 暗色',
    summary: 'GitHub 风格暗色，蓝色强调与柔和前景',
    theme: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      cursor: '#58a6ff',
      cursorAccent: '#0d1117',
      selectionBackground: '#1f6feb66',
      selectionInactiveBackground: '#30363d',
      scrollbarSliderBackground: '#8b949e33',
      scrollbarSliderHoverBackground: '#8b949e66',
      scrollbarSliderActiveBackground: '#8b949e80',
      black: '#484f58',
      red: '#ff7b72',
      green: '#3fb950',
      yellow: '#d29922',
      blue: '#58a6ff',
      magenta: '#bc8cff',
      cyan: '#39c5cf',
      white: '#b1bac4',
      brightBlack: '#6e7681',
      brightRed: '#ffa198',
      brightGreen: '#56d364',
      brightYellow: '#e3b341',
      brightBlue: '#79c0ff',
      brightMagenta: '#d2a8ff',
      brightCyan: '#56d4dd',
      brightWhite: '#f0f6fc',
    },
  },
  {
    key: 'tokyo-night',
    label: 'Tokyo Night',
    summary: '冷静蓝紫底色，语法色区分清晰',
    theme: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      cursor: '#c0caf5',
      cursorAccent: '#1a1b26',
      selectionBackground: '#33467c',
      selectionInactiveBackground: '#292e42',
      scrollbarSliderBackground: '#c0caf533',
      scrollbarSliderHoverBackground: '#c0caf566',
      scrollbarSliderActiveBackground: '#c0caf580',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  {
    key: 'dracula',
    label: 'Dracula',
    summary: '经典紫灰底色，高饱和 ANSI 配色',
    theme: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      cursorAccent: '#282a36',
      selectionBackground: '#44475a',
      selectionInactiveBackground: '#3a3d4c',
      scrollbarSliderBackground: '#f8f8f233',
      scrollbarSliderHoverBackground: '#f8f8f266',
      scrollbarSliderActiveBackground: '#f8f8f280',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    key: 'monokai',
    label: 'Monokai',
    summary: '深灰底与明亮语法色，适合日志巡检',
    theme: {
      background: '#272822',
      foreground: '#f8f8f2',
      cursor: '#f8f8f0',
      cursorAccent: '#272822',
      selectionBackground: '#49483e',
      selectionInactiveBackground: '#3e3d32',
      scrollbarSliderBackground: '#f8f8f233',
      scrollbarSliderHoverBackground: '#f8f8f266',
      scrollbarSliderActiveBackground: '#f8f8f280',
      black: '#272822',
      red: '#f92672',
      green: '#a6e22e',
      yellow: '#f4bf75',
      blue: '#66d9ef',
      magenta: '#ae81ff',
      cyan: '#a1efe4',
      white: '#f8f8f2',
      brightBlack: '#75715e',
      brightRed: '#f92672',
      brightGreen: '#a6e22e',
      brightYellow: '#f4bf75',
      brightBlue: '#66d9ef',
      brightMagenta: '#ae81ff',
      brightCyan: '#a1efe4',
      brightWhite: '#f9f8f5',
    },
  },
  {
    key: 'solarized-light',
    label: 'Solarized 浅色',
    summary: '低眩光浅色终端，适合白天环境',
    theme: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#268bd2',
      cursorAccent: '#fdf6e3',
      selectionBackground: '#eee8d5',
      selectionInactiveBackground: '#f3ead2',
      scrollbarSliderBackground: '#657b8333',
      scrollbarSliderHoverBackground: '#657b8366',
      scrollbarSliderActiveBackground: '#657b8380',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    key: 'netcatty-light',
    label: 'Netcatty 浅色',
    summary: '清爽文档感，适合亮色工作台',
    theme: {
      background: '#f6f8fa',
      foreground: '#24292f',
      cursor: '#0969da',
      cursorAccent: '#ffffff',
      selectionBackground: '#0969da33',
      selectionInactiveBackground: '#d8dee4',
      scrollbarSliderBackground: '#57606a33',
      scrollbarSliderHoverBackground: '#57606a66',
      scrollbarSliderActiveBackground: '#57606a80',
      black: '#24292f',
      red: '#cf222e',
      green: '#116329',
      yellow: '#4d2d00',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#a40e26',
      brightGreen: '#1a7f37',
      brightYellow: '#9a6700',
      brightBlue: '#218bff',
      brightMagenta: '#a475f9',
      brightCyan: '#3192aa',
      brightWhite: '#8c959f',
    },
  },
  {
    key: 'hacker-green',
    label: 'Classic Green',
    summary: '复古绿色 phosphor，适合专注单色输出',
    theme: {
      background: '#07130d',
      foreground: '#9fffb8',
      cursor: '#00ff66',
      cursorAccent: '#07130d',
      selectionBackground: '#00ff6633',
      selectionInactiveBackground: '#123f25',
      scrollbarSliderBackground: '#9fffb833',
      scrollbarSliderHoverBackground: '#9fffb866',
      scrollbarSliderActiveBackground: '#9fffb880',
      black: '#07130d',
      red: '#ff6b6b',
      green: '#00ff66',
      yellow: '#d9ff6b',
      blue: '#67d8ff',
      magenta: '#c792ea',
      cyan: '#5fffd2',
      white: '#d8ffe2',
      brightBlack: '#31513d',
      brightRed: '#ff8585',
      brightGreen: '#6dff9e',
      brightYellow: '#e9ff93',
      brightBlue: '#9be8ff',
      brightMagenta: '#dfb6ff',
      brightCyan: '#9affea',
      brightWhite: '#ffffff',
    },
  },
];

export const terminalFontWeightChoices: ReadonlyArray<{ value: number; label: string }> = [
  { value: 300, label: '300 细' },
  { value: 400, label: '400 常规' },
  { value: 500, label: '500 中等' },
  { value: 600, label: '600 半粗' },
];

export const terminalBoldWeightChoices: ReadonlyArray<{ value: number; label: string }> = [
  { value: 600, label: '600 半粗' },
  { value: 700, label: '700 粗体' },
  { value: 800, label: '800 特粗' },
];

export function getTerminalTheme(themeKey: GuiSshAppSettings['terminalTheme']): ITheme {
  return terminalThemeChoices.find((themeChoice) => themeChoice.key === themeKey)?.theme ?? terminalThemeChoices[0].theme;
}

export function getTerminalThemeChoice(themeKey: GuiSshAppSettings['terminalTheme']) {
  return terminalThemeChoices.find((themeChoice) => themeChoice.key === themeKey) ?? terminalThemeChoices[0];
}

export function buildTerminalFontStack(fontFamily: GuiSshAppSettings['terminalFontFamily']) {
  const families = [
    fontFamily,
    'Cascadia Mono',
    'JetBrains Mono',
    'Consolas',
    'Menlo',
    'Monaco',
    'monospace',
  ];

  return [...new Set(families)]
    .map((family) => (family === 'monospace' ? family : `"${family}"`))
    .join(', ');
}

export function toTerminalFontWeight(weight: number): FontWeight {
  return weight;
}
