// Generated by scripts/generate-ipc-channel-map.cjs. Do not edit by hand.
// The map binds each Rust IPC channel to the public guiSSH method that defines
// its renderer-facing argument tuple and return type.

export const ipcChannelBindings = {
  'agent-sessions:delete': 'agentSessions.delete',
  'agent-sessions:get': 'agentSessions.get',
  'agent-sessions:save': 'agentSessions.save',
  'ai:chat': 'ai.chat',
  'ai:chat-stream': 'ai.chatStream',
  'ai:export-mcp-skill': 'ai.exportMcpSkill',
  'ai:list-models': 'ai.listModels',
  'ai:mcp-server-status': 'ai.getMcpServerStatus',
  'ai:set-mcp-server-enabled': 'ai.setMcpServerEnabled',
  'ai:web-search': 'ai.webSearch',
  'app:check-for-update-download': 'app.checkForUpdateDownload',
  'app:check-for-updates': 'app.checkForUpdates',
  'app:download-update': 'app.downloadUpdate',
  'app:get-info': 'app.getInfo',
  'app:get-update-status': 'app.getUpdateStatus',
  'app:install-update': 'app.installUpdate',
  'app:open-agent-window': 'app.openAgentWindow',
  'app:open-connection-window': 'app.openConnectionWindow',
  'app:open-external': 'app.openExternal',
  'app:open-main-ai-settings': 'app.openMainAiSettings',
  'app:open-sftp-transfer-window': 'app.openSftpTransferWindow',
  'app:show-main-window': 'app.showMainWindow',
  'config:export': 'files.exportConfig',
  'config:import': 'files.importConfig',
  'config:select-host-import-files': 'files.selectHostImportFiles',
  'connection:ack-terminal-output': 'connections.acknowledgeTerminalOutput',
  'connection:browser-resolve-url': 'connections.resolveBrowserUrl',
  'connection:cancel-transfer': 'connections.cancelTransfer',
  'connection:check-sftp': 'connections.checkSftp',
  'connection:clear-finished-transfers': 'connections.clearFinishedTransfers',
  'connection:clickhouse-columns': 'connections.clickhouseColumns',
  'connection:clickhouse-connect': 'connections.clickhouseConnect',
  'connection:clickhouse-databases': 'connections.clickhouseDatabases',
  'connection:clickhouse-disconnect': 'connections.clickhouseDisconnect',
  'connection:clickhouse-query': 'connections.clickhouseQuery',
  'connection:clickhouse-tables': 'connections.clickhouseTables',
  'connection:close-terminal': 'connections.closeTerminal',
  'connection:compress': 'connections.compress',
  'connection:connect': 'connections.connect',
  'connection:create-directory': 'connections.createDirectory',
  'connection:create-file': 'connections.createFile',
  'connection:decompress': 'connections.decompress',
  'connection:delete-path': 'connections.deletePath',
  'connection:disconnect': 'connections.disconnect',
  'connection:download-file': 'connections.downloadFile',
  'connection:download-paths': 'connections.downloadPaths',
  'connection:get-info': 'connections.getInfo',
  'connection:get-ipc-capabilities': 'connections.getIpcCapabilities',
  'connection:get-metrics': 'connections.getMetrics',
  'connection:get-monitor-history': 'connections.getMonitorHistory',
  'connection:get-monitor-persistence-status': 'connections.getMonitorPersistenceStatus',
  'connection:get-status': 'connections.getStatus',
  'connection:get-system-info': 'connections.getSystemInfo',
  'connection:host-key-response': 'connections.respondHostKeyVerification',
  'connection:http-tunnel-delete': 'connections.httpTunnelDelete',
  'connection:http-tunnel-get': 'connections.httpTunnelGet',
  'connection:http-tunnel-post': 'connections.httpTunnelPost',
  'connection:http-tunnel-put': 'connections.httpTunnelPut',
  'connection:keyboard-interactive-response': 'connections.respondKeyboardInteractive',
  'connection:list-directory': 'connections.listDirectory',
  'connection:list-transfers': 'connections.listTransfers',
  'connection:mongo-collections': 'connections.mongoCollections',
  'connection:mongo-connect': 'connections.mongoConnect',
  'connection:mongo-databases': 'connections.mongoDatabases',
  'connection:mongo-disconnect': 'connections.mongoDisconnect',
  'connection:mongo-indexes': 'connections.mongoIndexes',
  'connection:mongo-query': 'connections.mongoQuery',
  'connection:mysql-columns': 'connections.mysqlColumns',
  'connection:mysql-connect': 'connections.mysqlConnect',
  'connection:mysql-databases': 'connections.mysqlDatabases',
  'connection:mysql-disconnect': 'connections.mysqlDisconnect',
  'connection:mysql-query': 'connections.mysqlQuery',
  'connection:mysql-tables': 'connections.mysqlTables',
  'connection:mysql-update-cell': 'connections.mysqlUpdateCell',
  'connection:open-local': 'connections.openLocal',
  'connection:port-forward-delete': 'connections.deletePortForward',
  'connection:port-forward-list': 'connections.listPortForwards',
  'connection:port-forward-save': 'connections.savePortForward',
  'connection:port-forward-start': 'connections.startPortForward',
  'connection:port-forward-stop': 'connections.stopPortForward',
  'connection:postgres-columns': 'connections.postgresColumns',
  'connection:postgres-connect': 'connections.postgresConnect',
  'connection:postgres-databases': 'connections.postgresDatabases',
  'connection:postgres-disconnect': 'connections.postgresDisconnect',
  'connection:postgres-query': 'connections.postgresQuery',
  'connection:postgres-schemas': 'connections.postgresSchemas',
  'connection:postgres-tables': 'connections.postgresTables',
  'connection:postgres-update-cell': 'connections.postgresUpdateCell',
  'connection:rdp-probe': 'connections.rdpProbe',
  'connection:rdp-start': 'connections.rdpStart',
  'connection:rdp-stop': 'connections.rdpStop',
  'connection:read-file': 'connections.readFile',
  'connection:redis-command': 'connections.redisCommand',
  'connection:redis-connect': 'connections.redisConnect',
  'connection:redis-delete-key': 'connections.redisDeleteKey',
  'connection:redis-disconnect': 'connections.redisDisconnect',
  'connection:redis-get-value': 'connections.redisGetValue',
  'connection:redis-keys': 'connections.redisKeys',
  'connection:redis-remove-list-item': 'connections.redisRemoveListItem',
  'connection:redis-scan': 'connections.redisScan',
  'connection:redis-set-value': 'connections.redisSetValue',
  'connection:remove-transfer': 'connections.removeTransfer',
  'connection:rename-path': 'connections.renamePath',
  'connection:resize-terminal': 'connections.resizeTerminal',
  'connection:run-command': 'connections.runCommand',
  'connection:run-command-stream': 'connections.runCommandStream',
  'connection:select-upload-files': 'connections.selectUploadFiles',
  'connection:select-upload-folders': 'connections.selectUploadFolders',
  'connection:set-monitor-persistence-enabled': 'connections.setMonitorPersistenceEnabled',
  'connection:set-monitor-thresholds': 'connections.setMonitorThresholds',
  'connection:set-path-permissions': 'connections.setPathPermissions',
  'connection:sftp-compare-directory': 'connections.sftpCompareDirectory',
  'connection:sftp-create-directory': 'connections.sftpCreateDirectory',
  'connection:sftp-create-file': 'connections.sftpCreateFile',
  'connection:sftp-delete-path': 'connections.sftpDeletePath',
  'connection:sftp-download-paths': 'connections.sftpDownloadPaths',
  'connection:sftp-enqueue-transfers': 'connections.sftpEnqueueTransfers',
  'connection:sftp-list-directory': 'connections.sftpListDirectory',
  'connection:sftp-rename-path': 'connections.sftpRenamePath',
  'connection:sftp-set-path-permissions': 'connections.sftpSetPathPermissions',
  'connection:sftp-stat-path': 'connections.sftpStatPath',
  'connection:sftp-upload-bytes': 'connections.sftpUploadBytes',
  'connection:sftp-upload-local-paths': 'connections.sftpUploadLocalPaths',
  'connection:sqlite-close': 'connections.sqliteClose',
  'connection:sqlite-columns': 'connections.sqliteColumns',
  'connection:sqlite-objects': 'connections.sqliteObjects',
  'connection:sqlite-open': 'connections.sqliteOpen',
  'connection:sqlite-query': 'connections.sqliteQuery',
  'connection:sqlite-schema': 'connections.sqliteSchema',
  'connection:sqlite-tables': 'connections.sqliteTables',
  'connection:sqlite-update-cell': 'connections.sqliteUpdateCell',
  'connection:start-terminal': 'connections.startTerminal',
  'connection:stat-path': 'connections.statPath',
  'connection:trust-browser-certificate': 'connections.trustBrowserCertificate',
  'connection:upload-file': 'connections.uploadFile',
  'connection:upload-files': 'connections.uploadFiles',
  'connection:upload-local-paths': 'connections.uploadLocalPaths',
  'connection:upload-paths': 'connections.uploadPaths',
  'connection:vnc-probe': 'connections.vncProbe',
  'connection:vnc-start': 'connections.vncStart',
  'connection:vnc-stop': 'connections.vncStop',
  'connection:write-file': 'connections.writeFile',
  'connection:write-terminal': 'connections.writeTerminal',
  'connection:write-terminal-binary': 'connections.writeTerminalBytes',
  'connection:zmodem-read-upload-file': 'connections.readZmodemUploadFile',
  'connection:zmodem-release-upload-files': 'connections.releaseZmodemUploadFiles',
  'connection:zmodem-save-file': 'connections.saveZmodemFile',
  'connection:zmodem-select-upload-files': 'connections.selectZmodemUploadFiles',
  'dialog:save-text-file': 'files.saveTextFile',
  'dialog:select-private-key': 'files.selectPrivateKeyFile',
  'dialog:select-public-key': 'files.selectPublicKeyFile',
  'files:create-local-directory': 'files.createLocalDirectory',
  'files:create-local-file': 'files.createLocalFile',
  'files:delete-local-path': 'files.deleteLocalPath',
  'files:list-local-directory': 'files.listLocalDirectory',
  'files:rename-local-path': 'files.renameLocalPath',
  'files:stat-local-path': 'files.statLocalPath',
  'logs:append-entry': 'logs.appendEntry',
  'logs:clear-entries': 'logs.clearEntries',
  'logs:get-entries': 'logs.getEntries',
  'logs:save-entries': 'logs.saveEntries',
  'plugins:get-security-policy': 'pluginSecurity.getPolicy',
  'plugins:list-security-audit': 'pluginSecurity.listAudit',
  'plugins:review-manifest': 'pluginSecurity.reviewManifest',
  'preferences:get': 'preferences.get',
  'preferences:set': 'preferences.set',
  'sync:get-config': 'sync.getConfig',
  'sync:run-now': 'sync.runNow',
  'sync:save-config': 'sync.saveConfig',
  'sync:test-webdav': 'sync.testWebDav',
  'system:list-fonts': 'system.listFonts',
  'system:read-known-hosts': 'system.readKnownHosts',
  'system:test-proxy': 'system.testProxy',
  'vault:generate-rsa-key-pair': 'vault.generateRsaKeyPair',
  'vault:get-bookmarks': 'vault.getBookmarks',
  'vault:get-default-settings': 'vault.getDefaultSettings',
  'vault:get-public-snapshot': 'vault.getPublicSnapshot',
  'vault:get-remote-connection-profile': 'vault.getRemoteConnectionProfile',
  'vault:get-snapshot': 'vault.getSnapshot',
  'vault:import-key-pair': 'vault.importKeyPair',
  'vault:save-bookmarks': 'vault.saveBookmarks',
  'vault:save-collections': 'vault.saveCollections',
  'vault:save-remote-connection-profile': 'vault.saveRemoteConnectionProfile',
  'window:close': 'window.close',
  'window:is-maximized': 'window.isMaximized',
  'window:minimize': 'window.minimize',
  'window:show': 'window.show',
  'window:start-dragging': 'window.startDragging',
  'window:toggle-maximize': 'window.toggleMaximize',
} as const;

export type IpcChannel = keyof typeof ipcChannelBindings;

type AnyMethod = (...args: any[]) => any;
type PathValue<T, Path extends string> =
  Path extends `${infer Head}.${infer Tail}`
    ? Head extends keyof T
      ? PathValue<T[Head], Tail>
      : never
    : Path extends keyof T
      ? T[Path]
      : never;
type BoundMethod<Channel extends IpcChannel> = Extract<
  PathValue<ShellDeskApi, (typeof ipcChannelBindings)[Channel]>,
  AnyMethod
>;

interface IpcChannelSpec<Args extends unknown[], Result> {
  args: Args;
  result: Result;
}

interface IpcChannelOverrides {
  'ai:chat-stream': IpcChannelSpec<
    [request: ShellDeskAiChatRequest & { streamId: string }],
    ShellDeskAiChatResult
  >;
  'connection:connect': IpcChannelSpec<
    [host: ShellDeskHostConnectionRequest],
    { ok?: boolean; error?: string; connection?: ShellDeskConnectionInfo }
  >;
  'connection:open-local': IpcChannelSpec<
    [],
    { ok?: boolean; error?: string; connection?: ShellDeskConnectionInfo }
  >;
  'connection:run-command-stream': IpcChannelSpec<
    [
      connectionId: string,
      command: string,
      stdin: string | undefined,
      streamId: string,
      options?: { sudoPassword?: string },
    ],
    { stdout: string; stderr: string; code: number }
  >;
}

export type IpcChannelMap = {
  [Channel in IpcChannel]:
    Channel extends keyof IpcChannelOverrides
      ? IpcChannelOverrides[Channel]
      : IpcChannelSpec<
          Parameters<BoundMethod<Channel>>,
          Awaited<ReturnType<BoundMethod<Channel>>>
        >;
};

export type IpcArgs<Channel extends IpcChannel> = IpcChannelMap[Channel]['args'];
export type IpcResult<Channel extends IpcChannel> = IpcChannelMap[Channel]['result'];
